module.exports = {
  name: "Super User",
  username: "superuser",
  password: "234",
  privillages: [
    "Customers",
    "Add New Customers",
    "Add New Vendors",
    "Delete Vendor",
    "View Transactions",
    "View Orders",
    "Update Customer",
    "Update Vendor",
    "Payment",
    "Dashboard",
    "Employees",
    "Add New Employees",
    "Give User",
    "Delete Employee",
    "Update Employee",
    "Adminstration",
    "Users",
    "Access",
    "Reset User",
    "Delete User",
   "Charge User",
   "Disable User",
   "Add New Users",
   "View Customers",
   "New Purchase",
   "Purchase Report",
   "Products",
   "Delete Product",
   "Update Product",
   "New Sale",
   "Categories",
   "Delete Category",
   "Delete Type",
    "Delete Customer",
    "Vendors",
    "Sale Report",
    "New Sale",
    "New Service",
    "Service Report",
    "Reports",
    "Update User",
    "Transactions",
    "Import Products",
    "Tests"
  ],
};

 